export const BoatData = [
  {
    id: "1",
    Name: "YACHT - 1",
    CardImage: "/images/boats/ALFA'S/1.jpg",
    location: "İstanbul",
    url: "yacht-1",
    height: "20",
    capacity: "15",
    food: "15",
    crew: "2",
    DetailImages: [
      "/images/boats/ALFA'S/1.jpg",
      "/images/boats/ALFA'S/2.jpg",
      "/images/boats/ALFA'S/3.jpg",
      "/images/boats/ALFA'S/4.jpg",
      "/images/boats/ALFA'S/5.jpg",
      "/images/boats/ALFA'S/6.jpg",
    ],
  },
  {
    id: "2",
    Name: "YACHT - 2",
    CardImage: "/images/boats/AMESIN/10.jpeg",
    location: "İstanbul",
    url: "yacht-2",
    height: "24",
    capacity: "31",
    food: "31",
    crew: "3",
    DetailImages: [
      "/images/boats/AMESIN/1.jpeg",
      "/images/boats/AMESIN/2.jpeg",
      "/images/boats/AMESIN/3.jpeg",
      "/images/boats/AMESIN/4.jpeg",
      "/images/boats/AMESIN/5.jpeg",
      "/images/boats/AMESIN/6.jpeg",
      "/images/boats/AMESIN/7.jpeg",
      "/images/boats/AMESIN/8.jpeg",
      "/images/boats/AMESIN/9.jpeg",
      "/images/boats/AMESIN/10.jpeg",
      "/images/boats/AMESIN/11.jpeg",
      "/images/boats/AMESIN/12.jpeg",
      "/images/boats/AMESIN/13.jpeg",
    ],
  },
  {
    id: "3",
    Name: "YACHT - 3",
    CardImage: "/images/boats/BALTIK-2/1.jpg",
    location: "İstanbul",
    url: "yacht-3",
    height: "19",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/BALTIK-2/1.jpg",
      "/images/boats/BALTIK-2/2.jpg",
      "/images/boats/BALTIK-2/3.jpg",
      "/images/boats/BALTIK-2/4.jpg",
      "/images/boats/BALTIK-2/5.jpg",
      "/images/boats/BALTIK-2/6.jpg",
      "/images/boats/BALTIK-2/7.jpg",
      "/images/boats/BALTIK-2/8.jpg",
      "/images/boats/BALTIK-2/9.jpg",
      "/images/boats/BALTIK-2/10.jpg",
      "/images/boats/BALTIK-2/11.jpg",
    ],
  },
  {
    id: "4",
    Name: "YACHT - 4",
    CardImage: "/images/boats/BELLA/1.jpg",
    location: "İstanbul",
    url: "yacht-4",
    height: "20",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/BELLA/1.jpg",
      "/images/boats/BELLA/2.jpg",
      "/images/boats/BELLA/3.jpg",
      "/images/boats/BELLA/4.jpg",
      "/images/boats/BELLA/5.jpg",
      "/images/boats/BELLA/6.jpg",
      "/images/boats/BELLA/7.jpg",
      "/images/boats/BELLA/8.jpg",
      "/images/boats/BELLA/9.jpg",
      "/images/boats/BELLA/10.jpg",
    ],
  },
  {
    id: "5",
    Name: "BODRUM 1",
    CardImage: "/images/boats/BODRUM-1/1.jpg",
    location: "Muğla",
    url: "bodrum-1",
    height: "19",
    capacity: "12",
    food: "10",
    crew: "3",
    DetailImages: [
      "/images/boats/BODRUM-1/1.jpg",
      "/images/boats/BODRUM-1/2.jpg",
      "/images/boats/BODRUM-1/3.jpg",
      "/images/boats/BODRUM-1/4.jpg",
      "/images/boats/BODRUM-1/5.jpg",
      "/images/boats/BODRUM-1/6.jpg",
      "/images/boats/BODRUM-1/7.jpg",
      "/images/boats/BODRUM-1/8.jpg",
      "/images/boats/BODRUM-1/9.jpg",
      "/images/boats/BODRUM-1/10.jpg",
      "/images/boats/BODRUM-1/11.jpg",
      "/images/boats/BODRUM-1/12.jpg",
      "/images/boats/BODRUM-1/13.jpg",
      "/images/boats/BODRUM-1/14.jpg",
      "/images/boats/BODRUM-1/15.jpg",
      "/images/boats/BODRUM-1/16.jpg",
      "/images/boats/BODRUM-1/17.jpg",
    ],
    phone: "+905320589978",

  },
  {
    id: "6",
    Name: "BODRUM 2 ",
    CardImage: "/images/boats/BODRUM-2/1.jpg",
    location: "Muğla",
    url: "bodrum-2",
    height: "19",
    capacity: "15",
    food: "12",
    crew: "2",

    DetailImages: [
      "/images/boats/BODRUM-2/1.jpg",
      "/images/boats/BODRUM-2/2.jpg",
      "/images/boats/BODRUM-2/3.jpg",
      "/images/boats/BODRUM-2/4.jpg",
      "/images/boats/BODRUM-2/5.jpg",
      "/images/boats/BODRUM-2/6.jpg",
      "/images/boats/BODRUM-2/7.jpg",
      "/images/boats/BODRUM-2/8.jpg",
      "/images/boats/BODRUM-2/9.jpg",
      "/images/boats/BODRUM-2/10.jpg",
      "/images/boats/BODRUM-2/11.jpg",
      "/images/boats/BODRUM-2/12.jpg",
      "/images/boats/BODRUM-2/13.jpg",
      "/images/boats/BODRUM-2/14.jpg",
      "/images/boats/BODRUM-2/15.jpg",
      "/images/boats/BODRUM-2/16.jpg",
      "/images/boats/BODRUM-2/17.jpg",
    ],
    phone: "+905320589978",

  },
  {
    id: "7",
    Name: "YACHT - 5",
    CardImage: "/images/boats/BOGAZ-COCUGU/1.jpg",
    location: "İstanbul",
    url: "yacht-5",
    height: "19",
    capacity: "12",
    food: "10",
    crew: "2",
    DetailImages: [
      "/images/boats/BOGAZ-COCUGU/1.jpg",
      "/images/boats/BOGAZ-COCUGU/2.jpg",
      "/images/boats/BOGAZ-COCUGU/3.jpg",
      "/images/boats/BOGAZ-COCUGU/4.jpg",
      "/images/boats/BOGAZ-COCUGU/5.jpg",
      "/images/boats/BOGAZ-COCUGU/6.jpg",
      "/images/boats/BOGAZ-COCUGU/7.jpg",
      "/images/boats/BOGAZ-COCUGU/8.jpg",
      "/images/boats/BOGAZ-COCUGU/9.jpg",
      "/images/boats/BOGAZ-COCUGU/10.jpg",
    ],
  },
  {
    id: "8",
    Name: "YACHT - 6",
    CardImage: "/images/boats/CALIENTE/1.jpg",
    location: "İstanbul",
    url: "yacht-6",
    height: "19",
    capacity: "12",
    food: "12",
    crew: "3",
    DetailImages: [
      "/images/boats/CALIENTE/1.jpg",
      "/images/boats/CALIENTE/2.jpg",
      "/images/boats/CALIENTE/3.jpg",
      "/images/boats/CALIENTE/4.jpg",
      "/images/boats/CALIENTE/5.jpg",
    ],
  },
  {
    id: "9",
    Name: "YACHT - 7",
    CardImage: "/images/boats/FANTASY/1.jpg",
    location: "İstanbul",
    url: "yacht-7",
    height: "21",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/FANTASY/1.jpg",
      "/images/boats/FANTASY/2.jpg",
      "/images/boats/FANTASY/3.jpg",
      "/images/boats/FANTASY/4.jpg",
      "/images/boats/FANTASY/5.jpg",
      "/images/boats/FANTASY/6.jpg",
    ],
  },
  {
    id: "10",
    Name: "YACHT - 8",
    CardImage: "/images/boats/HYPNOS/1.jpg",
    location: "İstanbul",
    url: "yacht-8",
    height: "22",
    capacity: "12",
    food: "10",
    crew: "2",
    DetailImages: [
      "/images/boats/HYPNOS/1.jpg",
      "/images/boats/HYPNOS/2.jpg",
      "/images/boats/HYPNOS/3.jpg",
      "/images/boats/HYPNOS/4.jpg",
      "/images/boats/HYPNOS/5.jpg",
      "/images/boats/HYPNOS/6.jpg",
    ],
  },
  {
    id: "18",
    Name: "YACHT - 9",
    CardImage: "/images/boats/WHITE-HORSE/1.jpg",
    location: "İstanbul",
    url: "yacht-9",
    height: "20",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/WHITE-HORSE/1.jpg",
      "/images/boats/WHITE-HORSE/2.jpg",
      "/images/boats/WHITE-HORSE/3.jpg",
      "/images/boats/WHITE-HORSE/4.jpg",
      "/images/boats/WHITE-HORSE/5.jpg",
      "/images/boats/WHITE-HORSE/6.jpg",
      "/images/boats/WHITE-HORSE/7.jpg",
      "/images/boats/WHITE-HORSE/8.jpg",
      "/images/boats/WHITE-HORSE/9.jpg",
    ],
  },
  {
    id: "12",
    Name: "YACHT - 10",
    CardImage: "/images/boats/MELIS-K/1.jpg",
    location: "İstanbul",
    url: "yacht-10",
    height: "21",
    capacity: "15",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/MELIS-K/1.jpg",
      "/images/boats/MELIS-K/2.jpg",
      "/images/boats/MELIS-K/3.jpg",
      "/images/boats/MELIS-K/4.jpg",
      "/images/boats/MELIS-K/5.jpg",
      "/images/boats/MELIS-K/6.jpg",
      "/images/boats/MELIS-K/7.jpg",
      "/images/boats/MELIS-K/8.jpg",
    ],
  },
  {
    id: "13",
    Name: "YACHT - 11",
    CardImage: "/images/boats/MILENIUM/1.jpg",
    location: "İstanbul",
    url: "yacht-11",
    height: "21",
    capacity: "12",
    food: "10",
    crew: "6",
    DetailImages: [
      "/images/boats/MILENIUM/1.jpg",
      "/images/boats/MILENIUM/2.jpg",
      "/images/boats/MILENIUM/3.jpg",
      "/images/boats/MILENIUM/4.jpg",
      "/images/boats/MILENIUM/5.jpg",
      "/images/boats/MILENIUM/6.jpg",
      "/images/boats/MILENIUM/7.jpg",
      "/images/boats/MILENIUM/8.jpg",
      "/images/boats/MILENIUM/9.jpg",
      "/images/boats/MILENIUM/10.jpg",
    ],
  },
  {
    id: "14",
    Name: "YACHT - 12",
    CardImage: "/images/boats/ON-ROAD/1.jpg",
    location: "İstanbul",
    url: "yacht-12",
    height: "18",
    capacity: "12",
    food: "10",
    crew: "6",
    DetailImages: [
      "/images/boats/ON-ROAD/1.jpg",
      "/images/boats/ON-ROAD/2.jpg",
      "/images/boats/ON-ROAD/3.jpg",
      "/images/boats/ON-ROAD/4.jpg",
      "/images/boats/ON-ROAD/5.jpg",
      "/images/boats/ON-ROAD/6.jpg",
      "/images/boats/ON-ROAD/7.jpg",
      "/images/boats/ON-ROAD/8.jpg",
      "/images/boats/ON-ROAD/9.jpg",
      "/images/boats/ON-ROAD/10.jpg",
    ],
  },
  {
    id: "15",
    Name: "YACHT - 13",
    CardImage: "/images/boats/ORIENT/11.jpeg",
    location: "İstanbul",
    url: "yacht-13",
    height: "18",
    capacity: "10",
    food: "8",
    crew: "2",

    DetailImages: [
      "/images/boats/ORIENT/1.jpeg",
      "/images/boats/ORIENT/2.jpeg",
      "/images/boats/ORIENT/3.jpg",
      "/images/boats/ORIENT/4.jpg",
      "/images/boats/ORIENT/5.jpg",
      "/images/boats/ORIENT/6.jpg",
      "/images/boats/ORIENT/7.jpg",
      "/images/boats/ORIENT/8.jpg",
      "/images/boats/ORIENT/9.jpg",
      "/images/boats/ORIENT/10.jpg",
      "/images/boats/ORIENT/11.jpeg",
      "/images/boats/ORIENT/12.jpeg",
    ],
  },
  {
    id: "16",
    Name: "YACHT - 14",
    CardImage: "/images/boats/RIVER/1.jpg",
    location: "İstanbul",
    url: "yacht-14",
    height: "20",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/RIVER/1.jpg",
      "/images/boats/RIVER/2.jpg",
      "/images/boats/RIVER/3.jpg",
      "/images/boats/RIVER/4.jpg",
    ],
  },
  {
    id: "17",
    Name: "YACHT - 15",
    CardImage: "/images/boats/SELAMET-DAVUT/11.jpeg",
    location: "İstanbul",
    url: "yacht-15",
    height: "21",
    capacity: "30",
    food: "30",
    crew: "2",
    DetailImages: [
      "/images/boats/SELAMET-DAVUT/1.jpg",
      "/images/boats/SELAMET-DAVUT/2.jpg",
      "/images/boats/SELAMET-DAVUT/3.jpg",
      "/images/boats/SELAMET-DAVUT/4.jpg",
      "/images/boats/SELAMET-DAVUT/5.jpg",
      "/images/boats/SELAMET-DAVUT/6.jpeg",
      "/images/boats/SELAMET-DAVUT/7.jpeg",
      "/images/boats/SELAMET-DAVUT/8.jpeg",
      "/images/boats/SELAMET-DAVUT/9.jpeg",
      "/images/boats/SELAMET-DAVUT/10.jpeg",
      "/images/boats/SELAMET-DAVUT/11.jpeg",
    ],
  },
  {
    id: "18",
    Name: "BODRUM-3",
    CardImage: "/images/boats/ATA-BORA/1.jpg",
    location: "Muğla",
    url: "bodrum-3",
    height: "19",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/ATA-BORA/1.jpg",
      "/images/boats/ATA-BORA/2.jpg",
      "/images/boats/ATA-BORA/3.jpg",
      "/images/boats/ATA-BORA/4.jpg",
      "/images/boats/ATA-BORA/5.jpg",
      "/images/boats/ATA-BORA/6.jpg",
      "/images/boats/ATA-BORA/7.jpg",
      "/images/boats/ATA-BORA/8.jpg",
      "/images/boats/ATA-BORA/9.jpg",
      "/images/boats/ATA-BORA/10.jpg",
      "/images/boats/ATA-BORA/11.jpg",
    ],
    phone: "+905320589978",
  },
  {
    id: "19",
    Name: "YACHT-16",
    CardImage: "/images/boats/YACHT-16/1.jpeg",
    location: "İstanbul",
    url: "yacht-16",
    height: "19",
    capacity: "12",
    food: "12",
    crew: "2",
    DetailImages: [
      "/images/boats/YACHT-16/1.jpeg",
      "/images/boats/YACHT-16/2.jpeg",
      "/images/boats/YACHT-16/3.jpeg",
      "/images/boats/YACHT-16/4.jpeg",
      "/images/boats/YACHT-16/5.jpeg",
    ],
  },
  {
    id: "20",
    Name: "BODRUM-4",
    CardImage: "/images/boats/BODRUM-4/15.jpeg",
    location: "Muğla",
    url: "bodrum-4",
    height: "25",
    capacity: "12",
    food: "6",
    crew: "2",
    DetailImages: [
      "/images/boats/BODRUM-4/1.jpeg",
      "/images/boats/BODRUM-4/2.jpeg",
      "/images/boats/BODRUM-4/3.jpeg",
      "/images/boats/BODRUM-4/4.jpeg",
      "/images/boats/BODRUM-4/5.jpeg",
      "/images/boats/BODRUM-4/6.jpeg",
      "/images/boats/BODRUM-4/7.jpeg",
      "/images/boats/BODRUM-4/8.jpeg",
      "/images/boats/BODRUM-4/9.jpeg",
      "/images/boats/BODRUM-4/10.jpeg",
      "/images/boats/BODRUM-4/11.jpeg",
      "/images/boats/BODRUM-4/12.jpeg",
      "/images/boats/BODRUM-4/13.jpeg",
      "/images/boats/BODRUM-4/14.jpeg",
      "/images/boats/BODRUM-4/15.jpeg",
      "/images/boats/BODRUM-4/16.jpeg",
      "/images/boats/BODRUM-4/17.jpeg",
    ],
    phone: "+905320589978",

  },
  {
    id: "21",
    Name: "BODRUM-5",
    CardImage: "/images/boats/BODRUM-5/1.jpeg",
    location: "Muğla",
    url: "bodrum-5",
    height: "25",
    capacity: "8",
    food: "8",
    crew: "2",
    DetailImages: [
      "/images/boats/BODRUM-5/1.jpeg",
      "/images/boats/BODRUM-5/2.jpeg",
      "/images/boats/BODRUM-5/3.jpeg",
      "/images/boats/BODRUM-5/5.jpeg",
      "/images/boats/BODRUM-5/5.jpeg",
      "/images/boats/BODRUM-5/6.jpeg",
      "/images/boats/BODRUM-5/7.jpeg",
      "/images/boats/BODRUM-5/8.jpeg",
      "/images/boats/BODRUM-5/9.jpeg",
      "/images/boats/BODRUM-5/10.jpeg",
      "/images/boats/BODRUM-5/11.jpeg",
      "/images/boats/BODRUM-5/12.jpeg",
      "/images/boats/BODRUM-5/13.jpeg",
      "/images/boats/BODRUM-5/14.jpeg",
      "/images/boats/BODRUM-5/15.jpeg",
      "/images/boats/BODRUM-5/16.jpeg",
      "/images/boats/BODRUM-5/17.jpeg",
    ],
    phone: "+905320589978",

  },
  {
    id: "22",
    Name: "BODRUM-6",
    CardImage: "/images/boats/BODRUM-6/1.jpeg",
    location: "Muğla",
    url: "bodrum-6",
    height: "22",
    capacity: "15",
    food: "15",
    crew: "2",
    DetailImages: [
      "/images/boats/BODRUM-6/1.jpeg",
      "/images/boats/BODRUM-6/2.jpeg",
      "/images/boats/BODRUM-6/3.jpeg",
      "/images/boats/BODRUM-6/6.jpeg",
      "/images/boats/BODRUM-6/6.jpeg",
      "/images/boats/BODRUM-6/6.jpeg",
      "/images/boats/BODRUM-6/7.jpeg",
      "/images/boats/BODRUM-6/8.jpeg",
      "/images/boats/BODRUM-6/9.jpeg",
      "/images/boats/BODRUM-6/10.jpeg",
      "/images/boats/BODRUM-6/11.jpeg",
      "/images/boats/BODRUM-6/12.jpeg",
      "/images/boats/BODRUM-6/13.jpeg",
      "/images/boats/BODRUM-6/14.jpeg",
      "/images/boats/BODRUM-6/15.jpeg",
      "/images/boats/BODRUM-6/16.jpeg",
    ],
    phone: "+905320589978",

  },
  {
    id: "23",
    Name: "YACHT-17",
    CardImage: "/images/boats/YACHT-17/9.jpeg",
    location: "İstanbul",
    url: "yacht-17",
    height: "19",
    capacity: "10",
    food: "10",
    crew: "2",
    DetailImages: [
      "/images/boats/YACHT-17/1.jpeg",
      "/images/boats/YACHT-17/2.jpeg",
      "/images/boats/YACHT-17/3.jpeg",
      "/images/boats/YACHT-17/4.jpeg",
      "/images/boats/YACHT-17/5.jpeg",
      "/images/boats/YACHT-17/6.jpeg",
      "/images/boats/YACHT-17/7.jpeg",
      "/images/boats/YACHT-17/8.jpeg",
      "/images/boats/YACHT-17/9.jpeg",
      "/images/boats/YACHT-17/10.jpeg",
    ],
  },
  {
    id: "24",
    Name: "YACHT-18",
    CardImage: "/images/boats/YACHT-18/1.jpeg",
    location: "İstanbul",
    url: "yacht-18",
    height: "20",
    capacity: "22",
    food: "22",
    crew: "2",
    DetailImages: [
      "/images/boats/YACHT-18/1.jpeg",
      "/images/boats/YACHT-18/2.jpeg",
      "/images/boats/YACHT-18/3.jpeg",
      "/images/boats/YACHT-18/4.jpeg",
      "/images/boats/YACHT-18/5.jpeg",
      "/images/boats/YACHT-18/6.jpeg",
      "/images/boats/YACHT-18/7.jpeg",
    ],
  },
  {
    id: "25",
    Name: "YACHT-19",
    CardImage: "/images/boats/YACHT-19/5.jpeg",
    location: "İstanbul",
    url: "yacht-19",
    height: "21",
    capacity: "15",
    food: "15",
    crew: "2",
    DetailImages: [
      "/images/boats/YACHT-19/1.jpeg",
      "/images/boats/YACHT-19/2.jpeg",
      "/images/boats/YACHT-19/3.jpeg",
      "/images/boats/YACHT-19/4.jpeg",
      "/images/boats/YACHT-19/5.jpeg",
      "/images/boats/YACHT-19/6.jpeg",
      "/images/boats/YACHT-19/7.jpeg",
    ],
  },
  {
    id: "26",
    Name: "BODRUM-7",
    CardImage: "/images/boats/BODRUM-7/10.jpeg",
    location: "Muğla",
    url: "bodrum-7",
    height: "27",
    capacity: "15",
    food: "6",
    crew: "2",
    DetailImages: [
      "/images/boats/BODRUM-7/1.jpeg",
      "/images/boats/BODRUM-7/2.jpeg",
      "/images/boats/BODRUM-7/3.jpeg",
      "/images/boats/BODRUM-7/4.jpeg",
      "/images/boats/BODRUM-7/5.jpeg",
      "/images/boats/BODRUM-7/6.jpeg",
      "/images/boats/BODRUM-7/7.jpeg",
      "/images/boats/BODRUM-7/8.jpeg",
      "/images/boats/BODRUM-7/9.jpeg",
      "/images/boats/BODRUM-7/10.jpeg",
    ],
    phone: "+905320589978",

  },
  {
    id: "27",
    Name: "YACHT-20",
    CardImage: "/images/boats/YACHT-20/2.jpeg",
    location: "İstanbul",
    url: "yacht-20",
    height: "15",
    capacity: "30",
    food: "30",
    crew: "2",
    DetailImages: [
      "/images/boats/YACHT-20/1.jpeg",
      "/images/boats/YACHT-20/2.jpeg",
      "/images/boats/YACHT-20/3.jpeg",
      "/images/boats/YACHT-20/4.jpeg",
      "/images/boats/YACHT-20/5.jpeg",
    ],
  },
];
